language: objective-c
osx_image: xcode10.1

script:
    - set -o pipefail && xcodebuild -project KataString.xcodeproj -scheme 'KataString' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
